### ISSUE TITLE
Runtime failure when queue is full?

### ISSUE THREAD

**Issue by jasta** [ivmarkov/edge-executor#1]
Despite the spawn API having an option to return SpawnError::QueueFull, this doesn't seem to happen today and instead the call to `queue.push(runnable).unwrap()`  would just abort at runtime.  It's unclear how to solve this as I don't quite understand the relationship between Schedule and poll_one.  It seems to me there's not a 1:1 relationship, or better said, it seems possible that you could have multiple Runnable's enqueued for a single spawned future.  All the async-task examples and stuff seem to use unbounded queues and just punt on this problem so I'm wondering if maybe edge-executor will be forced to do the same?

**Comment by ivmarkov** [comment]
> Despite the spawn API having an option to return SpawnError::QueueFull, this doesn't seem to happen today and instead the call to `queue.push(runnable).unwrap()` would just abort at runtime. 

Indeed. The problem is - at the time - I found it next to impossible to implement a fallible contract for `spawn` (I could have missed something though). It goes like this:
- async-task does not provide any API to track how many tasks had been spawned on it (and are still alive)
- Even if it did, a task might complete, and after that it wont be scheduled anymore, so at that time you can actually spawn one extra task. And so on with each completing task

The whole limitation and the notion of "full" comes from nothing else but the fact, that the task scheduling queue happens to be bounded, as (1) I have not found a lock-free unbounded queue and (2) the unbounded ones - besides requiring locks would likely need allocations. Note that embassy-executor solves this elegantly by using intrusive list as the queue, but due to being completely static anyway has an upper limit on the number of tasks as you need to define these in the form of proc-macro annotated functions.

> It's unclear how to solve this as I don't quite understand the relationship between Schedule and poll_one.

As long as you have a natural limit on the number of tasks you plan to schedule, there is nothing to solve. Just create the executor with queue size N and then schedule your tasks there. Tasks on embedded anyway tend to be long living and bounded.

You can always of course re-tailor async-task with lockful unbounded, allocating queue, but I'm not sure there are many legit use cases for that in embedded.

> It seems to me there's not a 1:1 relationship, or better said, it seems possible that you could have multiple Runnable's enqueued for a single spawned future.

If you have N alive tasks at a moment in time, the queue will contain anything between 0 to N scheduled tasks, but no more. It is not possible to have one and the same task scheduled more than once in the queue. And I guess it is obvious by now that the queue contains all tasks which had been awoken by one of their wakers and thus need to run during `poll` of the executor.

> All the async-task examples and stuff seem to use unbounded queues and just punt on this problem so I'm wondering if maybe edge-executor will be forced to do the same?

See above. With fixed, estimated-at-compile-time, long-living tasks I'm not sure we are chasing a real problem.

With that said, you can surely use an unbounded, locking, allocating queue if you want to.

**Comment by jasta** [comment]
Ack'd, though this certainly makes things a lot less predictable at runtime.  My use case of is deploying a CoAP server that is using a dedicated spawned task for each long-running Observe client (kind of like HTTP long polling but formally supported by CoAP).  The CoAP server can limit the maximum number of these that can run concurrently, which is the right first line of defense against a denial of service I think, but this means that if there's a misalignment between the maximum task queue size and the maximum number of simultaneous connections I'll get a hard crash, no?  I can try to be conservative and just estimate that `C` must be say 4x greater than the max number of CoAP clients, but this can quickly fail if I start using the same executor for other tasks.  It'd certainly make the code a lot more predictable if the CoAP client would see a spawn error and could just deny the request in that case without breaking anything else...

Are you open to patches to make it possible to provide your own queue so that it can be unbounded at a minimum?

**Comment by jasta** [comment]
BTW big thanks for all this time you've taken to explain stuff to me as I'm trying to learn how to build for embedded the right way.  And not to forget all the guidance on my whacky tokio journey (which landed, yay!).  You're a big part of the reason I've kept going and have enjoyed doing this work so much.

**Comment by ivmarkov** [comment]
> Are you open to patches to make it possible to provide your own queue so that it can be unbounded at a minimum?

Sure, why not? Though that would likely mean that the executor - when running with an unbounded queue - cannot really be awoken from an ISR context, as that would mean that pushing a `Runnable` to the queue will happen from an ISR context. Which - in turn - means that you'll potentially call `malloc` from an ISR context which - at least on the ESP IDF - I think is not allowed, no?

Or if calling `malloc` from an ISR context would turn out to be OK, I think at the very least you need to protect pushing to the queue with a disable-all-interrupts critical section (`esp_idf_hal::interrupt::IsrCriticalSection`) so that the queue does not get messed up when a waker in a normal thread context tries to push to the queue, and gets interrupted in the middle by another waker running in an ISR context.

**Comment by ivmarkov** [comment]
One more thing: if you really want to go for an unbound queue, you might want to look into `async-task` itself, or even `tokio-rt`. I think the former at least did have an unbound queue by default. Surely not protected by a critical section mutex, but then the whole notify-from-an-ISR thing with an unbounded, allocating queue might be a no-go in the first place.

In that case, the work we do [here](https://github.com/esp-rs/esp-idf-hal/tree/async-drivers) should have an alternative implementation (perhaps, hidden behind a feature flag), where the drivers are not awaking the wakers directly from an ISR context but rather first awake a high priority FreeRTOS task (could be a shared singleton for all the drivers - a bit like the events' thread in the `async-io` reactor) and then the task awakes the executor using a regular waker, but that would be from a regular thread context, so an unbounded queue protected with - say - regular `std::sync::Mutex` would just work. Might be complex, but doable, with - say - FreeRTOS task notification, or FreeRTOS event sets. And given that the number of peripherals on the ESP32 is finite, that might just work as we would preallocate an event set or something which is as big as to accommodate notifications from every possible ESP32 peripheral. Just thinking loud...

**Comment by jasta** [comment]
Ok I'll need some time to digest all this, I was missing a lot of this context initially.  Thanks again for your thoughtful answer!

**Comment by ivmarkov** [comment]
> Ok I'll need some time to digest all this, I was missing a lot of this context initially. Thanks again for your thoughtful answer!

No worries and stop thanking me. We do need other folks looking into this!

And actually validating what I'm saying.

**Comment by ivmarkov** [comment]
I'm a copycat now, in that I've just overhauled `edge-executor` (tests pending) to be mostly a `no_std` replica of [async-executor](https://github.com/smol-rs/async-executor) with some minor, embedded-related features added on top.

As a side effect, it has a new feature - `unbounded` - that gives you an unbounded queue. Closing.

P.S. If you ask me, `async-executor` simply needs a PR to become `no_std`, and that'll probably happen as well (as long as the maintainers are open to that, given that both executors are anyway thin wrappers around the `async-task` heavy lifter).
